/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    lawyers: LawyerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    files: File;
    categories: Category;
    posts: Post;
    newsletter: Newsletter;
    managements: Management;
    board: Board;
    counselors: Counselor;
    'state-council-digests': StateCouncilDigest;
    'adjudicating-chamber': AdjudicatingChamber;
    'members-adjudicating-chamber': MembersAdjudicatingChamber;
    'ted-members': TedMember;
    composition: Composition;
    'ted-council-digests': TedCouncilDigest;
    'legislations-ted': LegislationsTed;
    'legislations-ted-types': LegislationsTedType;
    'calendar-ted': CalendarTed;
    commissions: Commission;
    'commission-members': CommissionMember;
    'commission-areas': CommissionArea;
    subsections: Subsection;
    'subsection-regions': SubsectionRegion;
    'subsection-members': SubsectionMember;
    'subsection-rooms': SubsectionRoom;
    'urh-honorarium': UrhHonorarium;
    legislations: Legislation;
    'legislations-types': LegislationsType;
    lawyers: Lawyer;
    events: Event;
    speakers: Speaker;
    registrations: Registration;
    certificates: Certificate;
    'participant-categories': ParticipantCategory;
    checkins: Checkin;
    search: Search;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    fileFolders: FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    fileFolders: {
      documentsAndFolders: 'fileFolders' | 'files';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    files: FilesSelect<false> | FilesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    newsletter: NewsletterSelect<false> | NewsletterSelect<true>;
    managements: ManagementsSelect<false> | ManagementsSelect<true>;
    board: BoardSelect<false> | BoardSelect<true>;
    counselors: CounselorsSelect<false> | CounselorsSelect<true>;
    'state-council-digests': StateCouncilDigestsSelect<false> | StateCouncilDigestsSelect<true>;
    'adjudicating-chamber': AdjudicatingChamberSelect<false> | AdjudicatingChamberSelect<true>;
    'members-adjudicating-chamber': MembersAdjudicatingChamberSelect<false> | MembersAdjudicatingChamberSelect<true>;
    'ted-members': TedMembersSelect<false> | TedMembersSelect<true>;
    composition: CompositionSelect<false> | CompositionSelect<true>;
    'ted-council-digests': TedCouncilDigestsSelect<false> | TedCouncilDigestsSelect<true>;
    'legislations-ted': LegislationsTedSelect<false> | LegislationsTedSelect<true>;
    'legislations-ted-types': LegislationsTedTypesSelect<false> | LegislationsTedTypesSelect<true>;
    'calendar-ted': CalendarTedSelect<false> | CalendarTedSelect<true>;
    commissions: CommissionsSelect<false> | CommissionsSelect<true>;
    'commission-members': CommissionMembersSelect<false> | CommissionMembersSelect<true>;
    'commission-areas': CommissionAreasSelect<false> | CommissionAreasSelect<true>;
    subsections: SubsectionsSelect<false> | SubsectionsSelect<true>;
    'subsection-regions': SubsectionRegionsSelect<false> | SubsectionRegionsSelect<true>;
    'subsection-members': SubsectionMembersSelect<false> | SubsectionMembersSelect<true>;
    'subsection-rooms': SubsectionRoomsSelect<false> | SubsectionRoomsSelect<true>;
    'urh-honorarium': UrhHonorariumSelect<false> | UrhHonorariumSelect<true>;
    legislations: LegislationsSelect<false> | LegislationsSelect<true>;
    'legislations-types': LegislationsTypesSelect<false> | LegislationsTypesSelect<true>;
    lawyers: LawyersSelect<false> | LawyersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    speakers: SpeakersSelect<false> | SpeakersSelect<true>;
    registrations: RegistrationsSelect<false> | RegistrationsSelect<true>;
    certificates: CertificatesSelect<false> | CertificatesSelect<true>;
    'participant-categories': ParticipantCategoriesSelect<false> | ParticipantCategoriesSelect<true>;
    checkins: CheckinsSelect<false> | CheckinsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    fileFolders: FileFoldersSelect<false> | FileFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (Lawyer & {
        collection: 'lawyers';
      });
  jobs: {
    tasks: {
      sendPostNotification: TaskSendPostNotification;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface LawyerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files".
 */
export interface File {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Quando marcado, o arquivo fica acessível publicamente sem autenticação
   */
  isPublic?: boolean | null;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fileFolders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'fileFolders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'files';
          value: number | File;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'files'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Define se a categoria aparece na home
   */
  highlight?: boolean | null;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Máximo de 320 caracteres
   */
  excerpt: string;
  featuredImage: number | File;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  categories: (number | Category)[];
  commission?: (number | null) | Commission;
  subsection?: (number | null) | Subsection;
  /**
   * Define se o post aparece na home
   */
  highlight?: boolean | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  relatedPosts?: (number | Post)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | File;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Marcado automaticamente quando o post é enviado aos inscritos da newsletter.
   */
  notificationSent?: boolean | null;
  /**
   * Calculado automaticamente com base no conteúdo.
   */
  readingTime?: number | null;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commissions".
 */
export interface Commission {
  id: number;
  title: string;
  type: 'permanente' | 'temporaria';
  area?: (number | null) | CommissionArea;
  /**
   * Vincule esta comissão a uma subseção específica.
   */
  subsection?: (number | null) | Subsection;
  /**
   * Texto exibido na seção "Sobre a Comissão".
   */
  about?: string | null;
  /**
   * Adicione as áreas de foco da comissão.
   */
  focusAreas?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commission-areas".
 */
export interface CommissionArea {
  id: number;
  title: string;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subsections".
 */
export interface Subsection {
  id: number;
  title: string;
  region: number | SubsectionRegion;
  /**
   * Data de fundação da subseção.
   */
  creationDate?: string | null;
  /**
   * Texto exibido na seção "Sobre a Subseção".
   */
  about?: string | null;
  mission?: string | null;
  street?: string | null;
  district?: string | null;
  city?: string | null;
  postalCode?: string | null;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  serviceHours?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subsection-regions".
 */
export interface SubsectionRegion {
  id: number;
  title: string;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter".
 */
export interface Newsletter {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  status?: ('active' | 'inactive') | null;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "managements".
 */
export interface Management {
  id: number;
  managementStart: number;
  managementEnd: number;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board".
 */
export interface Board {
  id: number;
  title: string;
  oabNumber: string;
  /**
   * Foto do membro da diretoria
   */
  photo?: (number | null) | File;
  management: number | Management;
  position:
    | 'presidente'
    | 'vice-presidente'
    | 'secretario-geral'
    | 'secretario-geral-adjunto'
    | 'tesoureiro'
    | 'tesoureiro-adjunto'
    | 'diretor-administrativo'
    | 'diretor-executivo'
    | 'diretor-relacoes-institucionais'
    | 'diretor-defesa-prerrogativas-valorizacao-advocacia'
    | 'diretor-educacao-juridica'
    | 'diretor-iniciacao-profissional'
    | 'diretor-tecnologia-inovacao'
    | 'diretor-inclusao-acessibilidade'
    | 'diretor-interiorizacao'
    | 'diretor-assuntos-penais'
    | 'diretor-atendimento'
    | 'diretor-relacionamento-justica-federal'
    | 'diretor-relacionamento-justica-estadual'
    | 'diretor-relacionamento-justica-trabalho'
    | 'diretor-relacionamento-justica-eleitoral'
    | 'conselho-estadual-titular'
    | 'conselho-estadual-suplente'
    | 'conselho-federal-titular'
    | 'conselho-federal-suplente';
  /**
   * Biografia institucional do(a) presidente
   */
  biography?: string | null;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "counselors".
 */
export interface Counselor {
  id: number;
  title: string;
  oabNumber: string;
  management: number | Management;
  councilType: 'estadual' | 'federal';
  positionType: 'titular' | 'suplente';
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "state-council-digests".
 */
export interface StateCouncilDigest {
  id: number;
  processNumber: string;
  acordaoNumber: string;
  year: number;
  information?: string | null;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adjudicating-chamber".
 */
export interface AdjudicatingChamber {
  id: number;
  title: string;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members-adjudicating-chamber".
 */
export interface MembersAdjudicatingChamber {
  id: number;
  title: string;
  oabNumber: string;
  adjudicatingChamber: number | AdjudicatingChamber;
  position: 'presidente' | 'vice-presidente' | 'relator' | 'relatora';
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ted-members".
 */
export interface TedMember {
  id: number;
  name: string;
  oabNumber: string;
  position?: ('presidente' | 'vice-presidente' | 'secretario-geral' | 'secretaria-geral') | null;
  isTurmaComposition?: boolean | null;
  /**
   * Selecione a composição. Campos adicionais aparecerão automaticamente ao salvar o membro se a composição contiver "Turma" no nome.
   */
  composition: number | Composition;
  /**
   * Local do membro
   */
  location?: string | null;
  /**
   * Selecione se o membro é titular ou suplente
   */
  memberType?: ('titular' | 'suplente') | null;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "composition".
 */
export interface Composition {
  id: number;
  title: string;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ted-council-digests".
 */
export interface TedCouncilDigest {
  id: number;
  processNumber: string;
  acordaoNumber: string;
  year: number;
  information?: string | null;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legislations-ted".
 */
export interface LegislationsTed {
  id: number;
  title: string;
  type: number | LegislationsTedType;
  file: number | File;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legislations-ted-types".
 */
export interface LegislationsTedType {
  id: number;
  title: string;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-ted".
 */
export interface CalendarTed {
  id: number;
  title: string;
  date: string;
  location: string;
  description?: string | null;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commission-members".
 */
export interface CommissionMember {
  id: number;
  name: string;
  oabNumber?: string | null;
  image?: (number | null) | File;
  commission: number | Commission;
  position: 'presidente' | 'vice-presidente' | 'secretario' | 'secretario-adjunto' | 'membro' | 'membro-consultivo';
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subsection-members".
 */
export interface SubsectionMember {
  id: number;
  name: string;
  oabNumber?: string | null;
  image?: (number | null) | File;
  subsection: number | Subsection;
  position:
    | 'presidente'
    | 'vice-presidente'
    | 'secretario-geral'
    | 'secretario-geral-adjunto'
    | 'tesoureiro'
    | 'conselheiro';
  management: number | Management;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subsection-rooms".
 */
export interface SubsectionRoom {
  id: number;
  title: string;
  subsection: number | Subsection;
  address: string;
  serviceHours?: string | null;
  phone?: string | null;
  email?: string | null;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "urh-honorarium".
 */
export interface UrhHonorarium {
  id: number;
  title: string;
  file: number | File;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legislations".
 */
export interface Legislation {
  id: number;
  title: string;
  type: number | LegislationsType;
  file: number | File;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legislations-types".
 */
export interface LegislationsType {
  id: number;
  title: string;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lawyers".
 */
export interface Lawyer {
  id: number;
  name: string;
  oabNumber?: string | null;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Gerenciamento de eventos e cursos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  type: 'event' | 'course' | 'conference' | 'workshop' | 'seminar' | 'lecture';
  /**
   * Interno: QR Code fixo no local. Externo: QR Code individual por ingresso.
   */
  eventType: 'internal' | 'external';
  modality: 'in-person' | 'hybrid' | 'virtual';
  startDate: string;
  endDate: string;
  startTime: string;
  endTime: string;
  commission?: (number | null) | Commission;
  subsection?: (number | null) | Subsection;
  /**
   * Nome do local onde será realizado
   */
  venue?: string | null;
  address?: string | null;
  city?: string | null;
  /**
   * URL para acesso à transmissão ao vivo
   */
  streamingUrl?: string | null;
  streamingPlatform?: ('youtube' | 'zoom' | 'teams' | 'meet' | 'other') | null;
  /**
   * Informações detalhadas sobre o evento
   */
  description: string;
  /**
   * Texto curto para exibição em cartões
   */
  shortDescription?: string | null;
  targetAudience?: string | null;
  /**
   * Total de horas do evento/curso
   */
  workload?: number | null;
  /**
   * Itens inclusos na inscrição
   */
  included?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Pré-requisitos para inscrição
   */
  requirements?:
    | {
        requirement: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Palestrantes confirmados para o evento
   */
  speakers?: (number | Speaker)[] | null;
  /**
   * Imagem principal do evento (recomendado: 1200x630px)
   */
  featuredImage: number | File;
  /**
   * Fotos adicionais do evento
   */
  gallery?:
    | {
        image: number | File;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Marque se o evento terá programações paralelas em diferentes salas
   */
  hasMultipleRooms?: boolean | null;
  /**
   * Adicione as salas do evento
   */
  rooms?:
    | {
        name: string;
        /**
         * Número máximo de participantes
         */
        capacity: number;
        floor?: string | null;
        description?: string | null;
        /**
         * Horários e atividades desta sala
         */
        roomSchedule?:
          | {
              date: string;
              startTime: string;
              endTime: string;
              title: string;
              speaker?: (number | null) | Speaker;
              sessionDescription?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  program?:
    | {
        date: string;
        time: string;
        title: string;
        briefDescription?: string | null;
        speaker?: (number | null) | Speaker;
        id?: string | null;
      }[]
    | null;
  registrationType: 'internal' | 'external';
  /**
   * Deixe vazio para sem limite
   */
  registrationLimit?: number | null;
  externalRegistrationUrl?: string | null;
  /**
   * Permite que um usuário compre ingressos para outras pessoas
   */
  allowMultipleTickets?: boolean | null;
  /**
   * Obriga o preenchimento dos dados de cada pessoa que usará os ingressos
   */
  requireTicketHolderData?: boolean | null;
  registrationStartDate?: string | null;
  registrationEndDate?: string | null;
  /**
   * Dias antes do evento até quando é permitido solicitar reembolso
   */
  refundDeadlineDays?: number | null;
  /**
   * Configure os tipos de ingresso e valores por categoria de participante
   */
  ticketTypes?:
    | {
        participantCategory: number | ParticipantCategory;
        price: number;
        /**
         * Limite por categoria
         */
        maxQuantity?: number | null;
        isActive?: boolean | null;
        description?: string | null;
        /**
         * Valor promocional antecipado
         */
        earlyBirdPrice?: number | null;
        earlyBirdDeadline?: string | null;
        id?: string | null;
      }[]
    | null;
  groupDiscountEnabled?: boolean | null;
  groupDiscountDescription?: string | null;
  /**
   * Configure as faixas de desconto progressivo
   */
  groupDiscountTiers?:
    | {
        minQuantity: number;
        /**
         * Deixe vazio para sem limite
         */
        maxQuantity?: number | null;
        discountPercent: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Código gerado automaticamente para validação de check-in
   */
  checkinPassword?: string | null;
  /**
   * QR Code fixo do evento (para eventos internos)
   */
  eventQRCode?: string | null;
  /**
   * Quantos minutos antes do evento o check-in é liberado
   */
  checkinStartMinutes?: number | null;
  /**
   * Marque se este evento/curso emite certificado de participação
   */
  hasCertificate?: boolean | null;
  /**
   * Template PDF para geração dos certificados
   */
  certificateTemplate?: (number | null) | File;
  /**
   * Título que aparecerá no certificado
   */
  certificateTitle?: string | null;
  /**
   * Use {NOME}, {EVENTO}, {DATA}, {CARGA_HORARIA} como variáveis
   */
  certificateDescription?: string | null;
  /**
   * Percentual mínimo de presença para ter direito ao certificado
   */
  minimumAttendancePercent?: number | null;
  /**
   * Permite que participantes emitam segunda via do certificado
   */
  allowDuplicateCertificate?: boolean | null;
  status: 'draft' | 'published' | 'registration-open' | 'registration-closed' | 'ongoing' | 'closed' | 'cancelled';
  /**
   * Exibir na página inicial
   */
  isFeatured?: boolean | null;
  registrationCount?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Palestrantes e apresentadores de eventos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers".
 */
export interface Speaker {
  id: number;
  name: string;
  professionalTitle: string;
  email?: string | null;
  phone?: string | null;
  /**
   * Biografia completa para exibição no site
   */
  bio?: string | null;
  /**
   * Texto curto para exibição em cartões e listagens
   */
  shortBio?: string | null;
  /**
   * Foto profissional (recomendado: 400x400px)
   */
  photo?: (number | null) | File;
  linkedin?: string | null;
  lattes?: string | null;
  website?: string | null;
  /**
   * Palestrantes inativos não aparecem nas listagens
   */
  isActive?: boolean | null;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Categorias de participantes para inscrição em eventos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participant-categories".
 */
export interface ParticipantCategory {
  id: number;
  name: string;
  /**
   * Identificador único para uso interno
   */
  code: string;
  description?: string | null;
  /**
   * Se marcado, o número da OAB será obrigatório na inscrição
   */
  requiresOAB?: boolean | null;
  /**
   * Se marcado, o CPF será obrigatório na inscrição
   */
  requiresCPF?: boolean | null;
  /**
   * Ordem em que a categoria aparece nas listagens
   */
  sortOrder?: number | null;
  /**
   * Categorias inativas não aparecem nas opções de inscrição
   */
  isActive?: boolean | null;
  /**
   * Cor hexadecimal para identificação visual
   */
  color?: string | null;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Inscrições em eventos e cursos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations".
 */
export interface Registration {
  id: number;
  registrationCode?: string | null;
  event: number | Event;
  registrantName: string;
  registrantCPF: string;
  registrantOAB?: string | null;
  registrantEmail: string;
  registrantPhone: string;
  /**
   * Usuário logado que realizou a inscrição
   */
  user?: (number | null) | User;
  /**
   * Adicione os dados de cada participante
   */
  tickets?:
    | {
        participantName: string;
        participantCPF: string;
        participantOAB?: string | null;
        participantEmail: string;
        participantPhone?: string | null;
        ticketType: number | ParticipantCategory;
        unitPrice?: number | null;
        ticketStatus?: ('active' | 'checked-in' | 'attended' | 'absent' | 'transferred' | 'cancelled') | null;
        /**
         * Token único para validação do ingresso
         */
        token?: string | null;
        /**
         * QR Code do ingresso para check-in
         */
        qrCode?: string | null;
        checkinAt?: string | null;
        /**
         * Funcionário que realizou o check-in
         */
        checkinBy?: (number | null) | User;
        id?: string | null;
      }[]
    | null;
  /**
   * Salas e horários escolhidos pelo participante
   */
  roomSelections?:
    | {
        roomId?: string | null;
        roomName?: string | null;
        date?: string | null;
        startTime?: string | null;
        endTime?: string | null;
        activityTitle?: string | null;
        id?: string | null;
      }[]
    | null;
  subtotal?: number | null;
  discountPercent?: number | null;
  discountAmount?: number | null;
  totalPrice?: number | null;
  groupDiscountApplied?: boolean | null;
  paymentStatus: 'pending' | 'processing' | 'paid' | 'failed' | 'refunded' | 'cancelled' | 'complimentary';
  paymentMethod?: ('boleto' | 'credit-card' | 'debit-card' | 'pix' | 'transfer' | 'complimentary') | null;
  paymentDate?: string | null;
  paymentReference?: string | null;
  notes?: string | null;
  adminNotes?: string | null;
  status: 'pending' | 'confirmed' | 'partial-checkin' | 'checked-in' | 'attended' | 'absent' | 'cancelled';
  registrationDate?: string | null;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  /**
   * Usuário que fez a última edição
   */
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Certificados de participação em eventos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: number;
  certificateNumber?: string | null;
  /**
   * Código para verificação de autenticidade
   */
  validationHash?: string | null;
  registration: number | Registration;
  event?: (number | null) | Event;
  /**
   * Índice do participante na inscrição (0 para o primeiro)
   */
  ticketIndex?: number | null;
  participantName?: string | null;
  participantCPF?: string | null;
  participantEmail?: string | null;
  eventTitle?: string | null;
  eventStartDate?: string | null;
  eventEndDate?: string | null;
  workload?: number | null;
  issuedAt?: string | null;
  isDuplicate?: boolean | null;
  /**
   * Número de vezes que o certificado foi baixado
   */
  downloadCount?: number | null;
  /**
   * Referência ao certificado original (para segunda via)
   */
  originalCertificateId?: (number | null) | Certificate;
  /**
   * QR Code para validação online do certificado
   */
  validationQRCode?: string | null;
  /**
   * Dados estruturados para geração do PDF
   */
  certificateData?: string | null;
  /**
   * Arquivo PDF do certificado gerado
   */
  pdfFile?: (number | null) | File;
  lastDownloadAt?: string | null;
  status?: ('pending' | 'generated' | 'sent' | 'error' | 'revoked') | null;
  errorMessage?: string | null;
  sentAt?: string | null;
  revokedAt?: string | null;
  revokedReason?: string | null;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registro de check-ins em eventos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkins".
 */
export interface Checkin {
  id: number;
  registration: number | Registration;
  event?: (number | null) | Event;
  participantName?: string | null;
  eventTitle?: string | null;
  /**
   * Índice do ingresso na inscrição (0 para o primeiro)
   */
  ticketIndex?: number | null;
  checkinType: 'manual' | 'automatic' | 'qr-individual';
  checkinMethod?: ('qr-code' | 'token' | 'manual-search' | 'list') | null;
  checkinAt: string;
  isValid?: boolean | null;
  /**
   * Voucher impresso foi apresentado
   */
  voucherValidated?: boolean | null;
  /**
   * Pagamento foi verificado no momento do check-in
   */
  paymentValidated?: boolean | null;
  /**
   * Participante foi marcado como presente
   */
  presenceConfirmed?: boolean | null;
  /**
   * Dados brutos do QR Code escaneado
   */
  qrCodeData?: string | null;
  tokenValidated?: boolean | null;
  ticketGenerated?: boolean | null;
  /**
   * QR Code para impressão no ticket/etiqueta
   */
  ticketQRCode?: string | null;
  ticketPrintedAt?: string | null;
  roomId?: string | null;
  roomName?: string | null;
  sessionTime?: string | null;
  notes?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  /**
   * Informações do dispositivo usado para check-in
   */
  deviceInfo?: string | null;
  /**
   * Usuário que realizou/validou o check-in
   */
  checkinBy?: (number | null) | User;
  /**
   * Usuário que criou este registro
   */
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Esta é uma lista de resultados de busca gerada automaticamente. Ela é usada na busca geral do site e é atualizada sozinha sempre que novos conteúdos são criados ou modificados no CMS.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  excerpt?: string | null;
  featuredImage?: (number | null) | File;
  publishedAt?: string | null;
  categories?:
    | {
        categoryId?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  populatedAuthors?:
    | {
        authorId?: string | null;
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | File;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Você precisará rebuildar o website ao alterar este campo.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'posts';
      value: number | Post;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'sendPostNotification' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'sendPostNotification' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'files';
        value: number | File;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'newsletter';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'managements';
        value: number | Management;
      } | null)
    | ({
        relationTo: 'board';
        value: number | Board;
      } | null)
    | ({
        relationTo: 'counselors';
        value: number | Counselor;
      } | null)
    | ({
        relationTo: 'state-council-digests';
        value: number | StateCouncilDigest;
      } | null)
    | ({
        relationTo: 'adjudicating-chamber';
        value: number | AdjudicatingChamber;
      } | null)
    | ({
        relationTo: 'members-adjudicating-chamber';
        value: number | MembersAdjudicatingChamber;
      } | null)
    | ({
        relationTo: 'ted-members';
        value: number | TedMember;
      } | null)
    | ({
        relationTo: 'composition';
        value: number | Composition;
      } | null)
    | ({
        relationTo: 'ted-council-digests';
        value: number | TedCouncilDigest;
      } | null)
    | ({
        relationTo: 'legislations-ted';
        value: number | LegislationsTed;
      } | null)
    | ({
        relationTo: 'legislations-ted-types';
        value: number | LegislationsTedType;
      } | null)
    | ({
        relationTo: 'calendar-ted';
        value: number | CalendarTed;
      } | null)
    | ({
        relationTo: 'commissions';
        value: number | Commission;
      } | null)
    | ({
        relationTo: 'commission-members';
        value: number | CommissionMember;
      } | null)
    | ({
        relationTo: 'commission-areas';
        value: number | CommissionArea;
      } | null)
    | ({
        relationTo: 'subsections';
        value: number | Subsection;
      } | null)
    | ({
        relationTo: 'subsection-regions';
        value: number | SubsectionRegion;
      } | null)
    | ({
        relationTo: 'subsection-members';
        value: number | SubsectionMember;
      } | null)
    | ({
        relationTo: 'subsection-rooms';
        value: number | SubsectionRoom;
      } | null)
    | ({
        relationTo: 'urh-honorarium';
        value: number | UrhHonorarium;
      } | null)
    | ({
        relationTo: 'legislations';
        value: number | Legislation;
      } | null)
    | ({
        relationTo: 'legislations-types';
        value: number | LegislationsType;
      } | null)
    | ({
        relationTo: 'lawyers';
        value: number | Lawyer;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'speakers';
        value: number | Speaker;
      } | null)
    | ({
        relationTo: 'registrations';
        value: number | Registration;
      } | null)
    | ({
        relationTo: 'certificates';
        value: number | Certificate;
      } | null)
    | ({
        relationTo: 'participant-categories';
        value: number | ParticipantCategory;
      } | null)
    | ({
        relationTo: 'checkins';
        value: number | Checkin;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'fileFolders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'lawyers';
        value: number | Lawyer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'lawyers';
        value: number | Lawyer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files_select".
 */
export interface FilesSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  isPublic?: T;
  createdBy?: T;
  editedBy?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  highlight?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  categories?: T;
  commission?: T;
  subsection?: T;
  highlight?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  relatedPosts?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  notificationSent?: T;
  readingTime?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter_select".
 */
export interface NewsletterSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  status?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "managements_select".
 */
export interface ManagementsSelect<T extends boolean = true> {
  managementStart?: T;
  managementEnd?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board_select".
 */
export interface BoardSelect<T extends boolean = true> {
  title?: T;
  oabNumber?: T;
  photo?: T;
  management?: T;
  position?: T;
  biography?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "counselors_select".
 */
export interface CounselorsSelect<T extends boolean = true> {
  title?: T;
  oabNumber?: T;
  management?: T;
  councilType?: T;
  positionType?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "state-council-digests_select".
 */
export interface StateCouncilDigestsSelect<T extends boolean = true> {
  processNumber?: T;
  acordaoNumber?: T;
  year?: T;
  information?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adjudicating-chamber_select".
 */
export interface AdjudicatingChamberSelect<T extends boolean = true> {
  title?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members-adjudicating-chamber_select".
 */
export interface MembersAdjudicatingChamberSelect<T extends boolean = true> {
  title?: T;
  oabNumber?: T;
  adjudicatingChamber?: T;
  position?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ted-members_select".
 */
export interface TedMembersSelect<T extends boolean = true> {
  name?: T;
  oabNumber?: T;
  position?: T;
  isTurmaComposition?: T;
  composition?: T;
  location?: T;
  memberType?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "composition_select".
 */
export interface CompositionSelect<T extends boolean = true> {
  title?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ted-council-digests_select".
 */
export interface TedCouncilDigestsSelect<T extends boolean = true> {
  processNumber?: T;
  acordaoNumber?: T;
  year?: T;
  information?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legislations-ted_select".
 */
export interface LegislationsTedSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  file?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legislations-ted-types_select".
 */
export interface LegislationsTedTypesSelect<T extends boolean = true> {
  title?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-ted_select".
 */
export interface CalendarTedSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  location?: T;
  description?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commissions_select".
 */
export interface CommissionsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  area?: T;
  subsection?: T;
  about?: T;
  focusAreas?:
    | T
    | {
        item?: T;
        id?: T;
      };
  generateSlug?: T;
  slug?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commission-members_select".
 */
export interface CommissionMembersSelect<T extends boolean = true> {
  name?: T;
  oabNumber?: T;
  image?: T;
  commission?: T;
  position?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commission-areas_select".
 */
export interface CommissionAreasSelect<T extends boolean = true> {
  title?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subsections_select".
 */
export interface SubsectionsSelect<T extends boolean = true> {
  title?: T;
  region?: T;
  creationDate?: T;
  about?: T;
  mission?: T;
  street?: T;
  district?: T;
  city?: T;
  postalCode?: T;
  phone?: T;
  email?: T;
  website?: T;
  serviceHours?: T;
  generateSlug?: T;
  slug?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subsection-regions_select".
 */
export interface SubsectionRegionsSelect<T extends boolean = true> {
  title?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subsection-members_select".
 */
export interface SubsectionMembersSelect<T extends boolean = true> {
  name?: T;
  oabNumber?: T;
  image?: T;
  subsection?: T;
  position?: T;
  management?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subsection-rooms_select".
 */
export interface SubsectionRoomsSelect<T extends boolean = true> {
  title?: T;
  subsection?: T;
  address?: T;
  serviceHours?: T;
  phone?: T;
  email?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "urh-honorarium_select".
 */
export interface UrhHonorariumSelect<T extends boolean = true> {
  title?: T;
  file?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legislations_select".
 */
export interface LegislationsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  file?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legislations-types_select".
 */
export interface LegislationsTypesSelect<T extends boolean = true> {
  title?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lawyers_select".
 */
export interface LawyersSelect<T extends boolean = true> {
  name?: T;
  oabNumber?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  eventType?: T;
  modality?: T;
  startDate?: T;
  endDate?: T;
  startTime?: T;
  endTime?: T;
  commission?: T;
  subsection?: T;
  venue?: T;
  address?: T;
  city?: T;
  streamingUrl?: T;
  streamingPlatform?: T;
  description?: T;
  shortDescription?: T;
  targetAudience?: T;
  workload?: T;
  included?:
    | T
    | {
        item?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        requirement?: T;
        id?: T;
      };
  speakers?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  hasMultipleRooms?: T;
  rooms?:
    | T
    | {
        name?: T;
        capacity?: T;
        floor?: T;
        description?: T;
        roomSchedule?:
          | T
          | {
              date?: T;
              startTime?: T;
              endTime?: T;
              title?: T;
              speaker?: T;
              sessionDescription?: T;
              id?: T;
            };
        id?: T;
      };
  program?:
    | T
    | {
        date?: T;
        time?: T;
        title?: T;
        briefDescription?: T;
        speaker?: T;
        id?: T;
      };
  registrationType?: T;
  registrationLimit?: T;
  externalRegistrationUrl?: T;
  allowMultipleTickets?: T;
  requireTicketHolderData?: T;
  registrationStartDate?: T;
  registrationEndDate?: T;
  refundDeadlineDays?: T;
  ticketTypes?:
    | T
    | {
        participantCategory?: T;
        price?: T;
        maxQuantity?: T;
        isActive?: T;
        description?: T;
        earlyBirdPrice?: T;
        earlyBirdDeadline?: T;
        id?: T;
      };
  groupDiscountEnabled?: T;
  groupDiscountDescription?: T;
  groupDiscountTiers?:
    | T
    | {
        minQuantity?: T;
        maxQuantity?: T;
        discountPercent?: T;
        id?: T;
      };
  checkinPassword?: T;
  eventQRCode?: T;
  checkinStartMinutes?: T;
  hasCertificate?: T;
  certificateTemplate?: T;
  certificateTitle?: T;
  certificateDescription?: T;
  minimumAttendancePercent?: T;
  allowDuplicateCertificate?: T;
  status?: T;
  isFeatured?: T;
  registrationCount?: T;
  generateSlug?: T;
  slug?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers_select".
 */
export interface SpeakersSelect<T extends boolean = true> {
  name?: T;
  professionalTitle?: T;
  email?: T;
  phone?: T;
  bio?: T;
  shortBio?: T;
  photo?: T;
  linkedin?: T;
  lattes?: T;
  website?: T;
  isActive?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations_select".
 */
export interface RegistrationsSelect<T extends boolean = true> {
  registrationCode?: T;
  event?: T;
  registrantName?: T;
  registrantCPF?: T;
  registrantOAB?: T;
  registrantEmail?: T;
  registrantPhone?: T;
  user?: T;
  tickets?:
    | T
    | {
        participantName?: T;
        participantCPF?: T;
        participantOAB?: T;
        participantEmail?: T;
        participantPhone?: T;
        ticketType?: T;
        unitPrice?: T;
        ticketStatus?: T;
        token?: T;
        qrCode?: T;
        checkinAt?: T;
        checkinBy?: T;
        id?: T;
      };
  roomSelections?:
    | T
    | {
        roomId?: T;
        roomName?: T;
        date?: T;
        startTime?: T;
        endTime?: T;
        activityTitle?: T;
        id?: T;
      };
  subtotal?: T;
  discountPercent?: T;
  discountAmount?: T;
  totalPrice?: T;
  groupDiscountApplied?: T;
  paymentStatus?: T;
  paymentMethod?: T;
  paymentDate?: T;
  paymentReference?: T;
  notes?: T;
  adminNotes?: T;
  status?: T;
  registrationDate?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  certificateNumber?: T;
  validationHash?: T;
  registration?: T;
  event?: T;
  ticketIndex?: T;
  participantName?: T;
  participantCPF?: T;
  participantEmail?: T;
  eventTitle?: T;
  eventStartDate?: T;
  eventEndDate?: T;
  workload?: T;
  issuedAt?: T;
  isDuplicate?: T;
  downloadCount?: T;
  originalCertificateId?: T;
  validationQRCode?: T;
  certificateData?: T;
  pdfFile?: T;
  lastDownloadAt?: T;
  status?: T;
  errorMessage?: T;
  sentAt?: T;
  revokedAt?: T;
  revokedReason?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participant-categories_select".
 */
export interface ParticipantCategoriesSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  description?: T;
  requiresOAB?: T;
  requiresCPF?: T;
  sortOrder?: T;
  isActive?: T;
  color?: T;
  createdBy?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkins_select".
 */
export interface CheckinsSelect<T extends boolean = true> {
  registration?: T;
  event?: T;
  participantName?: T;
  eventTitle?: T;
  ticketIndex?: T;
  checkinType?: T;
  checkinMethod?: T;
  checkinAt?: T;
  isValid?: T;
  voucherValidated?: T;
  paymentValidated?: T;
  presenceConfirmed?: T;
  qrCodeData?: T;
  tokenValidated?: T;
  ticketGenerated?: T;
  ticketQRCode?: T;
  ticketPrintedAt?: T;
  roomId?: T;
  roomName?: T;
  sessionTime?: T;
  notes?: T;
  latitude?: T;
  longitude?: T;
  deviceInfo?: T;
  checkinBy?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  publishedAt?: T;
  categories?:
    | T
    | {
        categoryId?: T;
        title?: T;
        id?: T;
      };
  populatedAuthors?:
    | T
    | {
        authorId?: T;
        name?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fileFolders_select".
 */
export interface FileFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendPostNotification".
 */
export interface TaskSendPostNotification {
  input: {
    postId: string;
    postTitle: string;
    postExcerpt: string;
    postSlug: string;
    postImageUrl?: string | null;
  };
  output: {
    totalSubscribers?: number | null;
    emailsSent?: number | null;
    emailsFailed?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'posts';
      value: number | Post;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FileBlock".
 */
export interface FileBlock {
  file: number | File;
  id?: string | null;
  blockName?: string | null;
  blockType: 'fileBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}